backend = "glx";
glx-no-stencil = true;
glx-copy-from-front = false;

# Opacity
active-opacity = 1.0;
inactive-opacity = 1.0;
frame-opacity = 1;
inactive-opacity-override = false;

# opacity-rule = [
#   "85:class_g = 'org.wezfurlong.wezterm' && focused",
#   "85:class_g = 'org.wezfurlong.wezterm' && !focused",
# ];
#
# # Blur efect
# blur-background = true;
# blur-method = "dual_kawase";
# blur-strength = 6;
#
# blur-background-exclude = [
#   "window_type = 'dock'",
# ];
#
# Fading
fading = true;
fade-in-step = 0.03;
fade-out-step = 0.03;
fade-delta = 10;
no-fading-openclose = false;


fade-exclude = [];

# Others
mark-wmwin-focused = true;
mark-ovredir-focuesd = true;
detect-rounded-corners = true;
detect-client-opacity = true;
vsync = true;
dbe = false;
unredir-if-possible = false;
detect-transient = true;
detect-client-leader = true;

focus-exclude = [ ];

# Window rules
# wintypes:
# {
#   dock = {
#     shadow = false;
#   };
# };
#

# Shadow 
shadow = false;
shadow-radius = 12;
shadow-offset-x = -5;
shadow-offset-y = -5;
shadow-opacity = 0.5;
shadow-green = 1.0;

shadow-exclude = [
  "! name=''",
  "name = 'Notification'",
];

# Rounded corners
# corner-radius = 10;
# rounded-corners-exclude = [
# ];

xrender-sync-fence = true;
